// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpkywvrrwpmogwdbpcbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwa3l3dnJyd3Btb2d3ZGJwY2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjQ0MTcsImV4cCI6MjA3MjE0MDQxN30.6pWJITuOJ6xhklAUvuaeOvTis-dovpbjPzEZlYzhzLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});