// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwwktdntyojjkeaxofzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3d2t0ZG50eW9qamtlYXhvZnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODIzMjAsImV4cCI6MjA2OTM1ODMyMH0.pczf_n3TYQNG3ki3eiWLYL_dwIO41tMfOTBM-K0ROQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});